### ISSUE TITLE
Slow down transition

### ISSUE THREAD

**Issue by HarleyDavidson86** [multicolor-rgb/carousel-creator-bludit#1]
First of all: Thank you for this wonderful plugin!

Beside the settings I am missing the option to set the speed of the transition between two images.

Could you implement this or is there a way to set this value?

**Comment by multicolor-rgb** [comment]
yes, go to settings and check input " Time between next slider, if 0
-autoplay disable (milliseconds)"

**Comment by HarleyDavidson86** [comment]
This is the duration how long an image lasts before it switches to the next one but
I want to control the duration of the switch between two images. 

I found the value, it is in swipe.min.js at column 1499:
`y=a.speed||300`
When I change this to 
`y=a.speed||2000`
(I guess this is in milliseconds) the transition is slower.

**Comment by multicolor-rgb** [comment]
oh transition, i think about this:) No problem, maybe update soon :) If you like my work you can buy me coffe! With cofeine i work faster:P

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/carousel-creator-bludit/releases/tag/6.0.0
